spring:
  batch:
    job:
      enabled: false

server:
  port: 8081
  
jasypt:
  encryptor:
    bean: jasyptEncryptor
    secret: mykey

meta:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/_github/batch-sample/data/batch-meta.db
    username: ENC(HN3Y5j1JRF4y3DRXoPIJrA==)
    password: ENC(ajOdzzD7FDVoZ6SZegisXw==)

jobs:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/_github/batch-sample/data/batch-jobs.db
    username: ENC(HN3Y5j1JRF4y3DRXoPIJrA==)
    password: ENC(ajOdzzD7FDVoZ6SZegisXw==)
    populator: C:/_github/batch-sample/data/step2-schema.sql
  file:
    step1-input: C:/_github/batch-sample/data/step1-input-mass.csv
    step1-output: C:/_github/batch-sample/data/step1-output.xml
    step3-output: C:/_github/batch-sample/data/step3-output.json
